#!/usr/bin/env python
#
# Plugin to monitor status of Floating IPs in Nova
#
# To monitor instance states, link instance_states to this file.
# E.g.
#    ln -s /usr/share/munin/plugins/nova_instance_states /etc/munin/plugins/
#
# Needs following minimal configuration in plugin-conf.d/nova:
#   [nova_*]
#   user nova
#
# Magic markers
#%# capabilities=autoconf
#%# family=nova

from nova import context
from nova import db
from nova import flags
from nova import utils
import sys


ctxt = context.get_admin_context()
instances = db.instance_get_all(ctxt)
instance_counts = {}
for instance in instances:
    val = instance_counts.get(instance.state_description, 0) + 1
    instance_counts[instance.state_description] = val
states = instance_counts.keys()


def print_config():
    global states
    print 'graph_title Nova Instance States'
    print 'graph_vlabel %'
    print 'graph_args --base 1000 --lower-limit 0'
    print 'graph_category nova'
    print 'graph_scale no'
    print 'graph_info This graph shows the number of instances by state'
    for state in states:
        print '%s.label %s' % (state, state)
        print '%s.draw LINE2' % state
        print '%s.info %s IPs' % (state, state)


def get_status():
    global instance_counts
    return instance_counts


def print_values():
    status = get_status()
    for (state, value) in status.iteritems():
        print "%s.value %s" % (state, value)


if __name__ == '__main__':
    if len(sys.argv) > 1:
        if sys.argv[1] == "config":
            print_config()
        elif sys.argv[1] == "autoconf":
            print "yes"
    else:
        utils.default_flagfile()
        flags.FLAGS(sys.argv)
        print_values()
